Use gh cli to download build_number artifact

diff --git a/.github/workflows/build_xdrip.yml b/.github/workflows/build_xdrip.yml
--- a/.github/workflows/build_xdrip.yml
+++ b/.github/workflows/build_xdrip.yml
@@ -242,15 +242,20 @@ jobs:
           echo "id=" >> $GITHUB_OUTPUT
           exit 0
 
-      - name: Download build_number artifact
+      - name: Download artifact by ID
         if: steps.get-latest-artifact.outputs.id != ''
-        uses: actions/download-artifact@v4
-        with:
-          run-id: ${{ steps.get-latest-artifact.outputs.id }}
-          name: build_number
-          path: .
-        continue-on-error: true
-          
+        env:
+          GH_TOKEN: ${{ secrets.GH_PAT }}
+        run: |
+          artifact_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ steps.get-latest-artifact.outputs.id }}/artifacts --jq '.artifacts[] | select(.name == "build_number") | .id')
+          if [ -n "$artifact_id" ]; then
+            gh api repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip --output build_number.zip
+            unzip build_number.zip -d .
+          else
+            echo "Artifact not found."
+            exit 1
+          fi
+
       - name: Fallback if no artifact found
         if: steps.get-latest-artifact.outputs.id == ''
         run: echo "1" > build_number.txt
